[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sixpence"
version = "2.1.0"
description = "Simple Budget Manager"
readme = "README.md"
requires-python = ">=3.13,<4.0.0"
authors = [{ name = "Craig N. Caroon", email = "craig@caroon.org" }]
dependencies = [
    "arrow ~= 1.3.0",
    "flet[all] ~= 0.28.3",
    "inflector ~= 3.1.1",
    "PyYAML ~= 6.0.2",
    "screeninfo ~= 0.8.1",
    "tinydb ~= 4.8.2",
]

[tool.hatch.version]
path = "src/app/version.py"

[tool.hatch.envs.hatch-test]
default-args = ["src/tests"]
extra-dependencies = ["faker ~= 37.5"]

[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report; coverage html"

[tool.hatch.build.targets.sdist]
include = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/"]

[tool.coverage.run]
omit = ["src/tests/*"]

[tool.coverage.report]
fail_under = 90
include = ["src/*"]

[tool.flet]
org = "org.caroon"
product = "Sixpence"
company = "Caroon Dot Org"
copyright = "Copyright (C) 2025 by Craig N. Caroon"
# NOTE: YYMMDD
build_number = 250818

[tool.flet.app]
path = "src"
