from flet import Colors as ftc
# Icon Sizes
ICON_LARGE = 80
ICON_MEDIUM = 50


# Colors
COLOR_INCOME = ftc.GREEN_ACCENT_100
COLOR_INCOME_ALT = ftc.GREEN_ACCENT_400
COLOR_EXPENSE = ftc.RED_ACCENT_100
COLOR_EXPENSE_ALT = ftc.RED_100
